name: Run Pingu
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Line url'
        required: true
        default: 'https://store.line.me/stickershop/product/7082991/en'

jobs:
  run-pingu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py ${{ inputs.url }} -g

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'stickers'
          path: 'stickers/pingu'
